services:
  pgdatabase:
    image: postgres:17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
      - ./pgadmin-pgpass:/pgpass
    ports:
      - "8085:80"

  kestra:
    image: kestra/kestra:latest
    pull_policy: missing
    entrypoint: /bin/bash
    command: -c 'export KESTRA_CONFIGURATION_SECRET=$(echo -n "mysecret" | base64) && /app/kestra server standalone'
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - pgdatabase

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:
  kestra-data:
